services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "5000:5000"

  development:
    extends:
      service: app
    build:
      context: .
      target: development
    volumes:
      - ./todo_app:/todo_app/todo_app
    environment:
      - FLASK_DEBUG=true
    depends_on:
      - mongodb
    command: poetry run flask run --host=0.0.0.0

  production:
    extends:
      service: app
    build:
      context: .
      target: production
    environment:
      - FLASK_DEBUG=false
    command: poetry run gunicorn -b 0.0.0.0:5000 "todo_app.app:create_app()"

  test:
    extends:
      service: app
    build:
      context: .
      target: test
    volumes:
      - ./todo_app:/todo_app/todo_app
    environment:
      - FLASK_DEBUG=false
    depends_on:
      - mongodb
    command: poetry run pytest

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: to_do_list
    command: ["mongod", "--noauth"]

volumes:
  mongo_data:
