services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "5000:5000"

  development:
    extends:
      service: app
    build:
      context: .
      target: development
    volumes:
      - ./todo_app:/todo_app/todo_app
    environment:
      - FLASK_DEBUG=true
    command: poetry run gunicorn -b 0.0.0.0:5000 "todo_app.app:create_app()"

  production:
    extends:
      service: app
    build:
      context: .
      target: production
    environment:
      - FLASK_DEBUG=false
    command: poetry run gunicorn -b 0.0.0.0:5000 "todo_app.app:create_app()"
